spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/blog?allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 30000
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
